### PR TITLE
Add support for UNIX sockets

### PR DESCRIPTION
**Pull request by dkuryakin**

### CODE REVIEW

**Comment by jogo** [comment]
Thank you for the pull request,

Adding support for unix sockets makes a lot of since. It would be nice to add some documentation and testing around this change. If you would like we can add the tests and documentation for you.

**Comment by dkuryakin** [comment]
Not a problem. Will add docs/tests soon

**Comment by nichochar** [comment]
Hi @dkuryakin , we're excited about this contribution!, do you know when you will have a bit of free time to tackle a bit of docs/tests?

**Comment by WolverineFan** [comment]
This works pretty well, but you'll also want to avoid the `setsockopt` call when `no_delay` is set for a unix socket.

**Comment by jparise** [comment]
Closing in favor of #206.

**Pull request closed without merging**
