### PR TITLE
adding code coverage

### PR DESCRIPTION
**Pull request by 4383**
Trivial changes to add code coverage.

### CODE REVIEW

**Review by jparise — COMMENTED** [review]
Because we're using pytest, should we use this plugin?

https://pypi.org/project/pytest-cov/

**Comment by 4383** [comment]
That's not an obligation to use this plugin but that could be an option. As you want. It work with the current version, and it will work with the other plugin too.

**Comment by jparise** [comment]
Let's use pytest-cov because it appears to offer better pytest integration with regard to `sys.path` handling. It also supports subproccesses, in case we need that later.

**Comment by 4383** [comment]
Make sense. Done with the latest patch set.

**Review by jparise — APPROVED** [review]

**Pull request merged**
