### PR TITLE
travis: check readme and flake8

### PR DESCRIPTION
**Pull request by methane**
Run flake8 and `setup.py check -rs` on Travis.

### CODE REVIEW

**Comment by cgordon** [comment]
Would this fix the problem with pypi's processing of the README.rst? When I run rst2html on the long description I am still seeing these errors:

```
<stdin>:29: (WARNING/2) Cannot analyze code. Pygments package not found.
<stdin>:35: (WARNING/2) Cannot analyze code. Pygments package not found.
````

**Comment by methane** [comment]
Uh, Python 2.7.10 is required to check reST contains `code-block`.
See http://bugs.python.org/issue23063

**Comment by cgordon** [comment]
Hmm, so we should just remove the code-block sections then? I don't think we should drop Python 2.6 support just to get slightly better documentation.

**Comment by methane** [comment]
No. It's problem of only for `setup.py check`.
Travis runs it on Python 2.7.9 but the bug is fixed on 2.7.10.

**Comment by methane** [comment]
Python 3.4.3 fixed the bug but Travis uses Python 3.4.2 too...
We can't check README on Travis for now.

**Pull request closed without merging**
