### PR TITLE
Retry on EINTR while sock.recv() and sock.sendall()

### PR DESCRIPTION
**Pull request by methane**
See https://www.python.org/dev/peps/pep-0475/

### CODE REVIEW

**Comment by cgordon** [comment]
Is there any way to test these changes? I think I understand the rationale, but I haven't had time to dig through the relevant Python C code for socket handling to double check that it isn't already handling retries on EINTR.

**Comment by methane** [comment]
@cgordon What type of test do you want?
It's easy to add `OSError(errno.EINTR)` to `MockSocket`.  But it doesn't check about underlaying socket doesn't retry.
May I make sample script for demonstrate EINTR separated from unittest?

**Comment by methane** [comment]
https://gist.github.com/methane/59781ec74e00402e4c6b

In this script, client.recv() raises EINTR, but sendall() doesn't.

**Comment by methane** [comment]
I've made #47 since I don't like branch name "patch-2".

**Comment by cgordon** [comment]
Should I close this PR in favor of #47 ?

**Pull request closed without merging**
