### PR TITLE
Retry when sock.recv() raises EINTR

### PR DESCRIPTION
**Pull request by methane**
On Python 2.7 and 3.4, `sock.recv()` returns EINTR when it interrupted by signal.
https://gist.github.com/methane/59781ec74e00402e4c6b

Some web server uses signal to manage workers. So pymemcache should retry recv() when EINTR.

(Python 3.5 retries automatically. See https://www.python.org/dev/peps/pep-0475/ )

### CODE REVIEW

**Comment by methane** [comment]
I'm surprised by test for 767c47e was succeeded.
It fails on my Mac.

**Comment by cgordon** [comment]
Is the test working correctly on your Mac now? If so, I can merge this.

**Comment by methane** [comment]
> Is the test working correctly on your Mac now? If so, I can merge this.

Yes.

**Comment by cgordon** [comment]
Thanks!

**Pull request merged**
