### PR TITLE
Added Python 3.5 and 3.6 to the build

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
Seems like we need to rearrange the matrix :(

**Comment by jogo** [comment]
@thedrow thanks for the PR, we definitly should be testing against python 3.5 and 3.6.

I agree we need to rearrange the test matrix, would you like to do that, if not I would be happy to help.

We should also update the python classifiers in setup.y to reflect that we support 3.5 and 36.

**Comment by thedrow** [comment]
I added it to my TODO list. If I don't get to it in the next few days feel free to go ahead.

**Comment by jogo** [comment]
@thedrow https://github.com/pinterest/pymemcache/pull/171

**Comment by jogo** [comment]
merged as part of #171

**Pull request closed without merging**
